CREATE TABLE USUARIO(
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	sobrenome VARCHAR(100) NOT NULL,
	sexo CHAR(1) NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	logradouro VARCHAR(100),
    numero VARCHAR(10),
    complemento VARCHAR(20),
    bairro VARCHAR(20),
    cep VARCHAR(10),
    cidade VARCHAR(20),
    uf VARCHAR(20),
	email VARCHAR(50),
	senha VARCHAR(15)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;